### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by elf-pavlik** [Nitrokey/nitrokey-mozilla-plugins#1]
both _README.md_ and _doc/main.md_ have no content

**Comment by jans23** [comment]
Thanks for the ticket. I just added a short README.

**Comment by elf-pavlik** [comment]
maybe worth linking to https://www.tuxed.net/fkooman/blog/indiecert_nitrokey.html ?

**Comment by jans23** [comment]
Thanks. I added the link to the readme.
